import { US_STATE_ABBREVIATIONS } from '@/constants/us-state-abbreviations';

enum Parties {
  Alliance = 'Alliance Party',
  Constitution = 'Constitution Party',
  Democratic = 'Democratic Party',
  Green = 'Green Party',
  Libertarian = 'Libertarian Party',
  Republican = 'Republican Party',
  Unity = 'Unity Party of America',
  WorkingClass = 'Working Class Party',
  WorkingFamilies = 'Working Families Party',
  Independent = 'None (No Affiliation)',
}

/**
 * Mock data sourced from https://en.wikipedia.org/wiki/Political_parties_in_the_United_States
 * which can be used to simulate data returned from the RTC Rock API
 * /state_requirements endpoint until we are able to integrate it.
 */
export const MockData = {
  [US_STATE_ABBREVIATIONS.ALABAMA]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.ALASKA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.ARIZONA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.ARKANSAS]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.CALIFORNIA]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.COLORADO]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Unity,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.CONNECTICUT]: [
    Parties.Alliance,
    Parties.Democratic,
    Parties.Green,
    Parties.Republican,
    Parties.WorkingFamilies,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.DELAWARE]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.DISTRICT_OF_COLUMBIA]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.FLORIDA]: [
    Parties.Alliance,
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Unity,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.GEORGIA]: [Parties.Democratic, Parties.Republican],
  [US_STATE_ABBREVIATIONS.HAWAII]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.IDAHO]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.ILLINOIS]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.INDIANA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.IOWA]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.KANSAS]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.KENTUCKY]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.LOUISIANA]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MAINE]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MARYLAND]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MASSACHUSETTS]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MICHIGAN]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.WorkingClass,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MINNESOTA]: [
    Parties.Alliance,
    Parties.Democratic,
    Parties.Green,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MISSISSIPPI]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MISSOURI]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.MONTANA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NEBRASKA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NEVADA]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NEW_HAMPSHIRE]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NEW_JERSEY]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NEW_MEXICO]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.WorkingFamilies,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NEW_YORK]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.WorkingFamilies,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NORTH_CAROLINA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.NORTH_DAKOTA]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.OHIO]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.OKLAHOMA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.OREGON]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.WorkingFamilies,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.PENNSYLVANIA]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.RHODE_ISLAND]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.SOUTH_CAROLINA]: [
    Parties.Alliance,
    Parties.Constitution,
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.WorkingFamilies,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.SOUTH_DAKOTA]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.TENNESSEE]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.TEXAS]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.UTAH]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.VERMONT]: [
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.VIRGINIA]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.WASHINGTON]: [
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.WEST_VIRGINIA]: [
    Parties.Democratic,
    Parties.Green,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.WISCONSIN]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Republican,
    Parties.Independent,
  ],
  [US_STATE_ABBREVIATIONS.WYOMING]: [
    Parties.Constitution,
    Parties.Democratic,
    Parties.Libertarian,
    Parties.Republican,
    Parties.Independent,
  ],
};
