import type { NullablePartial } from './nullable-partial';
import type { USPSAddress } from './usps-address';

export type USPSData = NullablePartial<{
  standardizedAddress: USPSAddress;
  deliveryPointCode: string;
  deliveryPointCheckDigit: string;
  dpvConfirmation: string;
  dpvFootnote: string;
  dpvCmra: string;
  dpvVacant: string;
  dpvNoStat: string;
  dpvNoStatReasonCode: number;
  dpvDrop: string;
  dpvThrowback: string;
  dpvNonDeliveryDays: string;
  dpvNonDeliveryDaysValues: number;
  dpvNoSecureLocation: string;
  dpvPbsa: string;
  dpvDoorNotAccessible: string;
  dpvEnhancedDeliveryCode: string;
  carrierRoute: string;
  carrierRouteIndicator: string;
  ewsNoMatch: boolean;
  postOfficeCity: string;
  postOfficeState: string;
  abbreviatedCity: string;
  fipsCountyCode: string;
  county: string;
  elotNumber: string;
  elotFlag: string;
  lacsLinkReturnCode: string;
  lacsLinkIndicator: string;
  poBoxOnlyPostalCode: boolean;
  suitelinkFootnote: string;
  pmbDesignator: string;
  pmbNumber: string;
  addressRecordType: string;
  defaultAddress: boolean;
  errorMessage: string;
  cassProcessed: boolean;
}>;
